In [1]:
def installDeps():
    !pip install numpy scipy
    !pip install resampy tensorflow six
    !pip install youtube_dl
    !pip install ipywidgets
    !pip install pydub
    !pip install tqdm
    !pip install ffmpeg-python
    !apt-get install ffmpeg
#!python vggish_train_demo.py --num_batches 50 --train_vggish=False --checkpoint './vggish_model.ckpt'

from __future__ import print_function

from random import shuffle

import numpy as np
import tensorflow as tf
import os
import vggish_params
from pydub import AudioSegment
from audioUtils import readFolder
from audioModel import predict, train
from audioInput import getLaughTracks, getNoise, processWavFile, getSamplesForFiles, getSampleForFile
import IPython.display as ipd
from IPython.core.display import display, HTML
from audioDisplay import predictAudio
import random
import json
from audioUtils import downloadYtAndPrepareAudio


def download(id):
    downloadYtAndPrepareAudio(id, 'data', stripSilence=False)
    

In [5]:
preds, audio = predictAudio('data/5seconds_laugh.wav', 'audio_500', ['laugh', 'x'])    
#print(len(preds))
#predictAudio('data/test.wav', 'audio_500_62-100')



loading ./model/audio_500/20_20/model
INFO:tensorflow:Restoring parameters from ./vggish_model.ckpt
INFO:tensorflow:Restoring parameters from ./model/audio_500/20_20/model


In [3]:
def describe(path):    
    file = 'data/%s.wav' % path
    audio = AudioSegment.from_file(file, format="wav")
    samples = audio.get_array_of_samples()
    print(np.array(samples).shape)
    #print(audio.sample_width)
    #print(audio.frame_rate)
    #print(audio.channels)
    print(len(audio))
    
describe('5seconds_laugh')

describe('noise_5')

(442696,)
5019
(441000,)
5000


In [13]:
predictAudio('data/wGhg-htVnJ0/prepared.wav', 'audio_100', ['laugh', 'x'])

loading ./model/audio_100/20_20/model
INFO:tensorflow:Restoring parameters from ./vggish_model.ckpt
INFO:tensorflow:Restoring parameters from ./model/audio_100/20_20/model


(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
        0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
        1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1]),
 array([[[-4.60517019, -4.60517019, -4.60517019, ..., -4.60517019,
          -4.60517019, -4.60517019],
         [-4.60517019, -4.60517019, -4.60517019, ..., -4.60517019,
          -4.60517019, -4.60517019],
         [-4.60517019, -4.60517019, -4.60517019, ..., -4.60517019,
          -4.60517019, -4.60517019],
         ...,
         

In [6]:
download('n_2kDtk-DDc')
#download('wGhg-htVnJ0')

id n_2kDtk-DDc


In [9]:
download('4XOeYPS9Sag')

id 4XOeYPS9Sag


In [2]:
predictAudio('data/4XOeYPS9Sag.wav', 'audio_500', ['laugh', 'x'])

loading ./model/audio_500/77_100/model
INFO:tensorflow:Restoring parameters from ./vggish_model.ckpt
INFO:tensorflow:Restoring parameters from ./model/audio_500/77_100/model


(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]),
 array([[[-4.60517019, -4.60517019, -4.60517019, ..., -4.60517019,
          -4.60517019, -4.60517019],
         [-4.60517019, -4.60517019, -4.60517019, ..., -4.60517019,
          -4.60517019, -4.60517019],
         [-4.60516697, -4.60516689, -4.6051668 , ..., -4.59981105,
          -4.59126022, -4.57511919],
         ...,
         [22.00626271

In [3]:
predictAudio('data/7aOgZiNGh9c.wav', 'audio_500', ['laugh', 'x'])

loading ./model/audio_500/78_100/model
INFO:tensorflow:Restoring parameters from ./vggish_model.ckpt
INFO:tensorflow:Restoring parameters from ./model/audio_500/78_100/model


(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0]),
 array([[[-4.60517019, -4.60517019, -4.60517019, ..., -4.60517019,
          -4.60517019, -4.60517019],
         [ 1.2897458 ,  1.3472032 ,  1.40913492, ...,  5.97792396,
           5.73164928,  5.70875481],
         [ 9.86573826, 10.06496859, 10.21957629, ..., 13.15676969,
          12.35999101, 13.07929537],
         ...,
         [19.73505531, 19.82368643, 19.13344788, ..., 18.7293888 ,
          17.76702801, 17.69976925],
         [20.20441525, 20.14556661, 19.89333882, ..., 18.76549857,
          17.8341829 , 17.97353635],
         [18.96400452, 19.24699165, 19.74434456, ..., 19.03727028,
          18.42663436, 18.20567872]],
 
        [[19.7134070

In [4]:
file = 'j_pC0-Jfsq0'
predictAudio('data/%s.wav' % file, 'audio_500', ['laugh', 'x'])

loading ./model/audio_500/78_100/model
INFO:tensorflow:Restoring parameters from ./vggish_model.ckpt
INFO:tensorflow:Restoring parameters from ./model/audio_500/78_100/model


(array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [5]:
file = 'xLeBWcARXYo'
predictAudio('data/%s.wav' % file, 'audio_500', ['laugh', 'x'])

loading ./model/audio_500/79_100/model
INFO:tensorflow:Restoring parameters from ./vggish_model.ckpt
INFO:tensorflow:Restoring parameters from ./model/audio_500/79_100/model


(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
        1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
        1, 1, 0, 0, 0, 0, 0]),
 array([[[19.17594031, 19.41157256, 19.59526169, ..., 18.1570439 ,
          18.05243785, 17.87322767],
         [20.13285845, 20.7985044 , 21.10452591, ..., 18.62490995,
          18.52409927, 18.30043634],
         [19.53137905, 20.047866  , 19.33830877, ..., 18.48917319,
          18.60529192, 18.04364186],
         ...,
         [19.07297317, 18.22017979, 18.39550092, ..., 17.13390925,
          16.9650511 , 16.55669351],
         [18.78455777